name: build

on:
  push:
    branches: [ main, release-13.0.x, release-12.0.x ]
    tags:
      - "**"
  pull_request:
    branches: [ main, release-13.0.x, release-12.0.x ]

  # Run tests daily at 19:23 to get TYPO3 changes and fix them immediately.
  # @todo:
  #   * run only on dev-<TYPO3-LTS-branch/alias>
  #   * create issue on GH or message via TYPO3 Slack bot, if tests failed
  schedule:
    - cron:  '23 19 * * *'

env:
  IS_ON_GITHUB_ACTIONS: 'true'
  CI_BUILD_DIRECTORY: '/home/runner/work/ext-solr/ext-solr/.Build'
  LOCAL_IMAGE_NAME: 'solrci-image:latest'
  LOCAL_CONTAINER_NAME: 'solrci-container'
  TESTING_SOLR_PORT: 8983
  LOCAL_VOLUME_NAME: 'solrci-volume'
  LOCAL_VOLUME_PATH: '/home/runner/work/ext-solr/ext-solr/.Build/data-solr'
  BRANCH_NAME: 'main'

jobs:
  ci_bootstrapping:
    name: "Build and test docker image + Collect build matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect_build_matrix.outputs.matrix }}
    steps:
      # Workaround for issue with actions/checkout "wrong PR commit checkout":
      #   See:
      #   ** https://github.com/actions/checkout/issues/299#issuecomment-677674415
      #   ** https://github.com/actions/checkout/issues/1359#issuecomment-1631503791
      -
        name: Checkout current state of Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout current state of Branch
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: actions/checkout@v4
      # End: Workaround for issue with actions/checkout...
      -
        name: Collect build matrix
        id: collect_build_matrix
        run: |
          export matrix=$(cat .github/workflows/ci-matrix.json | jq --raw-output .\"${{ env.BRANCH_NAME }}\")
          echo "Base ref is $GITHUB_BASE_REF"
          echo "BRANCH_NAME="$BRANCH_NAME
          echo -e "matrix : "
          echo $matrix
          echo "matrix=$(echo $matrix)" >> $GITHUB_OUTPUT
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/SolrServer/Dockerfile
          tags: solrci-image:latest
          outputs: type=docker,dest=/tmp/solrci-image.tar
      -
        name: Test Image
        run: |
          pwd
          ls -la ../
          docker load --input /tmp/solrci-image.tar
          docker image ls -a
          ./Build/Test/cibuild_docker.sh
      -
        name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: solrci-image
          path: /tmp/solrci-image.tar
          retention-days: 1
      -
        name: Upload Solr-Server containers logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: solrci-logs
          path: /tmp/docker_image_logs_**/

  publish-docker-hub:
    name: Publish docker-image to docker-hub
    #needs: tests
    if: |
      (
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/heads/release-') ||
        startsWith(github.ref, 'refs/tags/')
      )
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS:  "linux/amd64,linux/arm64,linux/ppc64le"
      # @todo: replace with orig. ext-solr data
      DOCKER_HUB_IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/ext-solr"
      DOCKER_GITHUB_IMAGE_NAME: "ghcr.io/${{github.repository_owner}}/${{ github.event.repository.name }}"
      #DOCKER_IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/ext-solr"
      # is overridden below
      DOCKER_IMAGE_TAGS: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: enrich Environment Variables
        id: env
        run: |
          echo "NOW=$(date +'%F %Z %T')" >> $GITHUB_ENV
          echo "BRANCH_TAG=$(jq -r '.extra."branch-alias" | to_entries | .[0].key' composer.json)" >> $GITHUB_ENV
          echo "BRANCH_ALIAS_TAG=$(jq -r '.extra."branch-alias" | to_entries | .[0].value' composer.json)" >> $GITHUB_ENV

      - name: Debugging temp. MUST BE REMOVED before merging to EXT:solr
        # main branch without tags must become following tags:
        ## * dev-main
        ## * 13.0.x-dev
        # release-12.0.x branch without tags must become following tags:
        ## * dev-release-12.0.x
        ## * 12.0.x-dev
        run: |
          echo "NOW="${{ env.NOW }}
          echo "DOCKER_HUB_IMAGE_NAME="${{ env.DOCKER_HUB_IMAGE_NAME }}
          echo "DOCKER_GITHUB_IMAGE_NAME="${{ env.DOCKER_GITHUB_IMAGE_NAME }}
          echo "BRANCH_TAG="${{ env.BRANCH_TAG }}
          echo "BRANCH_ALIAS_TAG="${{ env.BRANCH_ALIAS_TAG }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_HUB_IMAGE_NAME }}

          tags: |
            type=raw,value=${{ env.BRANCH_TAG }}
            type=raw,value=${{ env.BRANCH_ALIAS_TAG }}
            # Only the newest major EXT:solr branch can become the latest tag.
            # So if main branch becomes dev state for next TYPO3 LTS, the latest tag must be commented there.
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=${{github.event.repository.name}}
            org.opencontainers.image.description=Docker image for Apache Solr for TYPO3 CMS EXT:solr extension
            org.opencontainers.image.vendor=${{github.repository_owner}}
            org.opencontainers.image.licenses=GPL-3.0,APACHE
            org.opencontainers.image.version=${{github.ref_name}}
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.url=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Appendix/DockerTweaks.html
            org.opencontainers.image.documentation=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Index.html

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/SolrServer/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
